AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Square API V1

Resources:
  SquareLamdafunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.handler
      Runtime: python3.8
      CodeUri: .
      Events:
        MyApi:
          Type: Api
          Properties:
            Path: /api/{proxy+} 
            Method: get