name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate with GCP
        uses: google-github-actions/setup-gcloud@v0.5.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Configure Docker
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/square-api:${{ github.sha }} .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/square-api:${{ github.sha }}


      - name: Deploy to GCP Compute Engine
        run: |
          # Run the necessary commands to deploy the Docker image to GCP Compute Engine
          # This could involve creating an instance, configuring networking, and running the Docker image

      - name: Cleanup
        run: |
          # Perform any necessary cleanup tasks, such as removing temporary resources or stopping instances
